# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-17 04:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='QCSSC',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qihao', models.CharField(max_length=10, verbose_name='期号')),
                ('wan', models.CharField(max_length=1, verbose_name='万')),
                ('qian', models.CharField(max_length=1, verbose_name='千')),
                ('bai', models.CharField(max_length=1, verbose_name='百')),
                ('shi', models.CharField(max_length=1, verbose_name='十')),
                ('ge', models.CharField(max_length=1, verbose_name='个')),
            ],
        ),
    ]
